chemical_data = {
    "FERRIC ALUM": "Ferric ammonium Sulfate offered by us is used mainly in the pulp and paper industry and as a flocculating agent or coagulant in water and waste treatment for clarifying and or purifying sewage and water for clarifying fats, oils, and petroleum products as a leather tanning agent as a pH stabilizer applied to soils to make it less alkaline or to produce acid conditions cement hardening accelerator; a mordant in dyeing anti-caking agent a fire extinguisher, a flame retardant additive and a foaming agent in firefighting foams. It is available in the form of Pale violet powder, Lumps/Slabs. We can offer it in many grades as per the application needs in different industry sectors.",
    "NON FERRIC ALUM": "Non-ferric alum is the purer form of ammonium sulfate. It has no ferric ions in its chemical composition. This substance is manufactured using aluminium trihydrate as the raw material. The raw material is reacted with sulfuric acid under suitable conditions to produce non-ferric alum.",
    "SOAP STONE POWDER": "Soapstone is a metamorphic rock that is widely known for various commercial applications. It serves as a raw material for the paint industry, paper industry, cosmetics, ceramics, etc. Such industry giants can only rely on harder grades of soapstone for their further production.",
    "CATIONIC STARCH": "Cationic Starch- A Quaternary ammonium derivative of starch principally as a wet-end additive in paper processing. Cationic Starch is much more than just a dry strength additive.",
    "MAIZE STARCH": "The diverse uses of starch make it a very versatile product. Maize or Corn Starch is a typical cereal starch with distinctly low protein and ash contents. Its carbohydrate content of high purity makes it useful in several industries. Some of these industries include the textile, paper, food, and pharmaceutical industries.",
    "OXIDISED STARCH": "Oxidised Starch is a modified oxidised starch in the form of superficially unchanged granules obtained by the action of chemicals on starch. It is specially designed for application in surface sizing/ coating for paper processing. It has got different viscosity and fluidity to sit the requirement of the paper.",
    "UREA FORMALDEHYDE": "afds",
    "FORTIFIED ROSIN": "afsd",
    "WHITENING AGENT": "asf",
    "DRY STRENGTH RESIN": "asdfgs",
    "GUAR GUM POWDER": "agdf",
    "FLOCULANT": "gaff",
    "RETENTION": "gfad",
    "BLEACHING POWDER": "agdf",
    "LIQUOR AMONIA": "agdf",
    "SURFACE SIZING CHEMICALS": "agdfa",
    "STICKIES CONTROL": "agdf",
    "TITANIUM DIOXIDE": "fgdad",
    "PAC LIQUID": "adggdfag",
    "ALL KINDS OF ENZYME": "gadf",
    "SODIUM HEXAMETA PHOSPHATE": "agdfg",
    "HYDROGEN PEROXIDE": "adfgddagad",
    "PIDICRYL": "adgfdafg",
    "GLOSS WHITE": "gdafadgf",
    "E.T.P. CHEMICALS": "afgdadg",
    "DEINKING CHEMICALS": "gfdagadgf",
    "SURFACTANT": "hfgh",
    "KAOLINE CLAY": "hadfgz",
}